const ActionTypes = {
  USER_LOGIN: 'USER_LOGIN',
  PLAYER_PLAY: 'PLAYER_PLAY',
  PLAYER_PAUSE: 'PLAYER_PAUSE',
  SET_NEXT_TRACK: 'SET_NEXT_TRACK',
  SET_PLAYING_PLAYLIST: 'SET_PLAYING_PLAYLIST',
  RECEIVE_USER_PLAYLIST_SUCCESS: 'RECEIVE_USER_PLAYLIST_SUCCESS',
  RECEIVE_USER_PLAYLIST_FAILURE: 'RECEIVE_USER_PLAYLIST_FAILURE',
  RECEIVE_PLAYLIST_DETAIL_SUCCESS: 'RECEIVE_PLAYLIST_DETAIL_SUCCESS',
  RECEIVE_PLAYLIST_DETAIL_FAILURE: 'RECEIVE_PLAYLIST_DETAIL_FAILURE',
  RECEIVE_AJAX_CALL_FAILURE: 'RECEIVE_AJAX_CALL_FAILUR',
  RECEIVE_TRACK_SUCCESS: 'RECEIVE_TRACK_SUCCESS',
  RECEIVE_TRACK_FAILURE: 'RECEIVE_TRACK_FAILURE',
}

export default ActionTypes