const ActionTypes = {
  USER_LOGIN: 'USER_LOGIN',
  RECEIVE_USER_PLAYLIST_SUCCESS: 'RECEIVE_USER_PLAYLIST_SUCCESS',
  RECEIVE_USER_PLAYLIST_FAILURE: 'RECEIVE_USER_PLAYLIST_FAILURE',
  RECEIVE_PLAYLIST_DETAIL_SUCCESS: 'RECEIVE_PLAYLIST_DETAIL_SUCCESS',
  RECEIVE_PLAYLIST_DETAIL_FAILURE: 'RECEIVE_PLAYLIST_DETAIL_FAILURE',
  RECEIVE_AJAX_CALL_FAILURE: 'RECEIVE_AJAX_CALL_FAILUR',
  RECEIVE_TRACK_SUCCESS: 'RECEIVE_TRACK_SUCCESS',
  RECEIVE_TRACK_FAILURE: 'RECEIVE_TRACK_FAILURE',
}

export default ActionTypes